#!/usr/bin/expect --

## From : http://aaronhawley.livejournal.com/10615.html
## Augmented to read from file

## timeout of an hour should be enough
set timeout 3600

set pid [spawn rpmbuild {*}$argv]

expect {
"^Enter pass phrase: " { send -- "[read [open "$env(HOME)/rpmbuild/.passphrase" r]]" ; exp_continue }
eof
}
